name: Check Omgevingsloket
on:
  schedule:
    - cron: '0 2 * * *' # Draait elke dag om 02:00 uur 's nachts
  workflow_dispatch:      # Handmatige knop blijft werken

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install requests geopandas pandas shapely
      - name: Run analyse
        run: python main.py
        env:
          DRY_RUN: "false" # Zet op "true" voor testen
