name: Check Omgevingsloket
on:
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Hier zet je de installatie-stap:
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analyse
        run: python main.py
        env:
          DRY_RUN: "true"
